// Theme handling: nativeTheme.themeSource follows the setting, and the app icon and window
// background follow the resolved theme (also when the OS appearance changes while on "system").
//
// Icons (generated by `pnpm icons` from resources/icons/*.svg):
//   macOS dock      icon-<theme>.png      1024 px, Apple icon grid (margin + shadow)
//   Windows/Linux   icon-<theme>-256.png  full-bleed window / taskbar icon

import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { app, nativeImage, nativeTheme, type BrowserWindow, type NativeImage } from 'electron';
import type { Appearance, MainContext } from './context';

const BACKGROUND = { dark: '#15181A', light: '#EAEDEA' } as const;

let iconDirCache: string | null = null;

/** Packaged: <resources>/icons (electron-builder extraResources). Dev: <project>/resources/icons. */
export function iconDir(): string {
  if (iconDirCache) return iconDirCache;
  if (app.isPackaged) return (iconDirCache = join(process.resourcesPath, 'icons'));
  // The bundle lives in <project>/<out dir>/main; walk up to find the project's resources.
  let dir = dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 4; i++) {
    const candidate = join(dir, 'resources', 'icons');
    if (existsSync(candidate)) return (iconDirCache = candidate);
    dir = dirname(dir);
  }
  return (iconDirCache = join(app.getAppPath(), 'resources', 'icons'));
}

export type IconUse = 'dock' | 'window';

export function iconFile(dark: boolean, use: IconUse): string {
  const theme = dark ? 'dark' : 'light';
  return use === 'dock' ? `icon-${theme}.png` : `icon-${theme}-256.png`;
}

const images = new Map<string, NativeImage>();

/** Cached icon image; null (with a warning) when the file is missing, e.g. before `pnpm icons`. */
export function iconImage(dark: boolean, use: IconUse): NativeImage | null {
  const file = iconFile(dark, use);
  let image = images.get(file);
  if (!image) {
    image = nativeImage.createFromPath(join(iconDir(), file));
    images.set(file, image);
    if (image.isEmpty()) console.warn(`[appearance] icon not found: ${join(iconDir(), file)} (run "pnpm icons")`);
  }
  return image.isEmpty() ? null : image;
}

export function createAppearance(ctx: MainContext): Appearance {
  const windows = new Set<BrowserWindow>();
  /** The resolved theme the icon and backgrounds were last updated for. */
  let applied: boolean | null = null;

  const isDark = () => nativeTheme.shouldUseDarkColors;

  function setDockIcon(dark: boolean): void {
    const image = iconImage(dark, 'dock');
    if (!image || !app.dock) return;
    app.dock.setIcon(image);
    if (ctx.isDev) console.log(`[appearance] dock icon -> ${join(iconDir(), iconFile(dark, 'dock'))}`);
  }

  /** Background color everywhere; the window icon on Windows and Linux. */
  function styleWindow(win: BrowserWindow, dark: boolean): void {
    if (win.isDestroyed()) return;
    win.setBackgroundColor(dark ? BACKGROUND.dark : BACKGROUND.light);
    if (process.platform === 'darwin') return;
    // Native window controls drawn over the top bar (titleBarOverlay) follow the panel colors.
    try {
      win.setTitleBarOverlay(titleBarOverlay(dark));
    } catch {
      // The window was created without an overlay.
    }
    const image = iconImage(dark, 'window');
    if (!image) return;
    win.setIcon(image);
    if (ctx.isDev) console.log(`[appearance] window icon -> ${join(iconDir(), iconFile(dark, 'window'))}`);
  }

  /** Updates icon and backgrounds when the resolved theme changed. Returns whether it did. */
  function sync(): boolean {
    if (!app.isReady()) return false;
    const dark = isDark();
    if (dark === applied) return false;
    applied = dark;
    if (process.platform === 'darwin') setDockIcon(dark);
    for (const win of windows) styleWindow(win, dark);
    return true;
  }

  nativeTheme.themeSource = ctx.store.getSettings().appearance.theme;
  void app.whenReady().then(sync);

  // Runs before index.ts broadcasts the settings, so the broadcast carries the new `dark`.
  ctx.store.onSettingsChanged((next, prev) => {
    if (next.appearance.theme === prev.appearance.theme) return;
    nativeTheme.themeSource = next.appearance.theme;
    sync();
  });

  // OS appearance changed (theme "system"). Theme changes made above were already applied,
  // so sync() reports no change for the 'updated' event they cause.
  nativeTheme.on('updated', () => {
    if (sync()) ctx.emit({ type: 'settings', settings: ctx.store.getSettings(), dark: isDark() });
  });

  return {
    isDark,
    attach(win) {
      windows.add(win);
      win.once('closed', () => windows.delete(win));
      styleWindow(win, isDark());
    },
  };
}

/**
 * Windows / Linux caption buttons over the 56px top bar: panel color (--p) with muted symbols (--mu).
 * 55px high so the bar's 1px bottom border stays visible under the buttons.
 */
export function titleBarOverlay(dark: boolean): { color: string; symbolColor: string; height: number } {
  return dark ? { color: '#1A1E20', symbolColor: '#7F8B85', height: 55 } : { color: '#F4F6F4', symbolColor: '#5B6B61', height: 55 };
}
